# Created by `nix-darwin`'s `homebrew` module

# Taps
tap "bryango/ccswitch"
tap "jundot/omlx"
tap "nohajc/anylinuxfs"

# Brews
brew "cocoapods"
brew "unbound"
brew "qwen-code"
brew "openclaw-cli"
brew "jundot/omlx/omlx"
brew "nohajc/anylinuxfs/anylinuxfs"

# Casks
cask "firefox"
cask "virtualbox"
cask "vlc"
cask "typeless"
cask "nutstore"
cask "zoom"
cask "visual-studio-code"
cask "tailscale-app"
cask "obsidian"
cask "yuanbao"
cask "notion"
cask "betterdisplay"
cask "lm-studio"
cask "codex-app"
cask "clash-verge-rev"
cask "chatgpt"
cask "daisydisk"
cask "claude-code"
cask "spotify"
cask "typora"
cask "whatsapp"
cask "iterm2"
cask "jellyfin"
cask "karabiner-elements"
cask "tunnelblick"
cask "racket"
cask "rustdesk"
cask "bryango/ccswitch/cc-switch"

