#!/bin/bash
# get the position of a package

CODE_VIEWER="@viewer@"

if [[ $# -gt 1 ]]; then
  CODE_VIEWER=$1
  shift
fi

package=$1
shift

pos=$(
    package=$package "@pkgsposition@" --raw --apply toString | xargs
)
>&2 echo "## $pos"

# shellcheck disable=2086
exec $CODE_VIEWER $pos
