#!/bin/bash
# get the position of a package

CODE_VIEWER=@viewer@

package=$1
shift

pos=$(
    package=$package "@pkgsposition@" --raw --apply toString | xargs
)

# shellcheck disable=2086
exec $CODE_VIEWER $pos
