#!/bin/bash
# get the position of a package

FILE=$HOME/@pkgslib@/pkgs-position.nix
CODE_VIEWER=@viewer@

package=$1
shift

pos=$(
    package=$package nix eval --impure --file "$FILE" \
        --raw --apply toString \
    | xargs
)

# shellcheck disable=2086
$CODE_VIEWER $pos
