name: "build cache"
on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0       ## not shallow
        filter: 'blob:none'  ## but blob-less
        submodules: true
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        install_url: https://releases.nixos.org/nix/nix-2.23.3/install
        extra_nix_config: |
          experimental-features = nix-command flakes fetch-closure configurable-impure-env
          impure-env = GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          trusted-users = @wheel
    - uses: cachix/cachix-action@v12
      with:
        name: chezbryan
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: ./build.sh --dry-run
    - run: ./build.sh
